/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FT_menu.home;

import FT_menu.navbar.Button_circle;
import javax.swing.JLabel;


/**
 *
 * @author mario
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    
    public Home() {
        initComponents();
        background_menu1.addBlurComponent(jPanel1);
    }
    
    public Button_circle getButton_menu_list() {
        return home_menu_list;
    }
    
    public JLabel getSteak_home_list() {
        return steak_menu_list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_menu1 = new FT_menu.home.Background_menu();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        home_menu_list = new FT_menu.navbar.Button_circle();
        button_circle2 = new FT_menu.navbar.Button_circle();
        steak_menu_list = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1650, 1020));

        background_menu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("STXingkai", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selamat Datang di REEK Restaurants.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 520, 30));

        jLabel5.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("life becomes a delicious adventure.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 720, 30));

        jLabel7.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pengalaman kuliner yang tak terlupakan menanti Anda di REEK restaurants.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 670, 30));

        jLabel8.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("REEK restaurants adalah aplikasi yang memudahkan pelanggan untuk ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 670, 30));

        jLabel9.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("memesan hidangan - hidangan lezat dari REEK restaurants");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 670, 30));

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("kualitas terbaik.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 270, 170, 30));

        jLabel10.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("pengalaman makan di tempat");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 300, 390, 30));

        jLabel11.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("yang praktis");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 130, 30));

        jLabel12.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("untuk melanjutkan ke");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1105, 490, 180, 30));

        jLabel13.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("be a journey to culinary delight. Because in the symphony of flavors,");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 720, 30));

        jLabel14.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Temukan berbagai pilihan makanan dan nikmati");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 390, 30));

        jLabel15.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("REEK restaurants menyajikan kuliner dengan");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 380, 30));

        jLabel16.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" tanpa mengantri atau delivery ke tempat tujuan");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 380, 30));

        jLabel17.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Enjoy your taste, savor the moments, and let every bite");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 440, 30));

        jLabel18.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("vibes.");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 130, 30));

        jLabel19.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Smile for");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 90, 30));

        jLabel20.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Klick Tombol (di pojok kiri bawah) atau");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 460, 360, 30));

        jLabel21.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Daging di bawah");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 140, 30));

        jLabel22.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ke Menu.");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, 140, 30));

        jLabel23.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setText("positive");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 60, 30));

        jLabel24.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("delicious food, start the day with");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 240, 280, 30));

        background_menu1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 66, 1340, 750));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/home/menu_12621818.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        jPanel2.add(home_menu_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 90));
        jPanel2.add(button_circle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 20, 190, 70));

        background_menu1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 830, 280, 130));

        steak_menu_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/home/a1.png"))); // NOI18N
        background_menu1.add(steak_menu_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 610, 510, 356));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FT_menu.home.Background_menu background_menu1;
    private FT_menu.navbar.Button_circle button_circle2;
    private FT_menu.navbar.Button_circle home_menu_list;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel steak_menu_list;
    // End of variables declaration//GEN-END:variables
}
