/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FT_menu.drink;

import FT_menu.ScrollBar;
import FT_menu.navbar.Button_circle;
import java.awt.Component;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import javax.swing.SwingUtilities;

/**
 *
 * @author mario
 */
public class Drink_home extends javax.swing.JPanel {

    /**
     * Creates new form Drink_home
     */
    private Event_drink event;
    
    public Drink_home() {
        initComponents();
        jScrollPane2.setVerticalScrollBar(new ScrollBar());
    }

    public void setEvent(Event_drink event) {
        this.event = event;
    }
    
    public void addItem(Drink_data data_d) {
        Item_drink item_d = new Item_drink();
        item_d.setData(data_d);
        item_d.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                if (SwingUtilities.isLeftMouseButton(me)) {
                    event.itemClick(item_d, data_d);
                }
            }
        
        });
        panelItem_drink1.add(item_d);
        panelItem_drink1.repaint();
        panelItem_drink1.revalidate();
    }
    
    public void setSelected(Component item) {
        for (Component com : panelItem_drink1.getComponents()) {
            Item_drink i = (Item_drink) com;
            if (i.isSelected()) {
                i.setSelected(false);
            }
        }
        ((Item_drink) item).setSelected(true);
    }
    
    public void showItem(Drink_data data_d) {
        LBitemNamed.setText(data_d.getItemName_d());
        txtpDescriptiond.setText(data_d.getDescription_d());
        LBbrandd.setText(data_d.getBrandName_d());
        DecimalFormat df = new DecimalFormat("Rp#,###");
        LBpriced.setText(df.format(data_d.getPrice_d()));
    }
    
    public Point getPanelItemLocation() {
        Point p = jScrollPane2.getLocation();
        return new Point(p.x, p.y-jScrollPane2.getViewport().getViewPosition().y);
    }
    
    public Button_circle getButton_add_d() {
        return button_add_d;
    }
    
    public Button_circle getButton_del_d() {
        return button_del_d;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        panelItem_drink1 = new FT_menu.drink.PanelItem_drink();
        jPanel1 = new javax.swing.JPanel();
        LBitemNamed = new javax.swing.JLabel();
        LBpriced = new javax.swing.JLabel();
        LBbrandd = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtpDescriptiond = new javax.swing.JTextPane();
        panel_drink_b1 = new FT_menu.drink.Panel_drink_b();
        jPanel2 = new javax.swing.JPanel();
        jLabel_add = new javax.swing.JLabel();
        add_icon = new javax.swing.JLabel();
        button_add_d = new FT_menu.navbar.Button_circle();
        add_menu_d = new FT_menu.navbar.Button_circle();
        jLabel_del = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        del_icon = new javax.swing.JLabel();
        button_del_d = new FT_menu.navbar.Button_circle();
        del_menu_d = new FT_menu.navbar.Button_circle();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1150, 675));

        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportView(panelItem_drink1);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(311, 411));

        LBitemNamed.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LBitemNamed.setForeground(new java.awt.Color(91, 91, 91));
        LBitemNamed.setText("Drink");

        LBpriced.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        LBpriced.setForeground(new java.awt.Color(91, 91, 91));
        LBpriced.setText("Rp.0.000");

        LBbrandd.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LBbrandd.setForeground(new java.awt.Color(87, 87, 87));
        LBbrandd.setText("Tipe");

        txtpDescriptiond.setBorder(null);
        txtpDescriptiond.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtpDescriptiond.setForeground(new java.awt.Color(145, 145, 145));
        txtpDescriptiond.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBitemNamed, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBpriced)
                    .addComponent(LBbrandd)
                    .addComponent(txtpDescriptiond, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(LBitemNamed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBpriced)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBbrandd)
                .addGap(6, 6, 6)
                .addComponent(txtpDescriptiond, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_drink_b1.setBlur(jPanel2);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_add.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel_add.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_add.setText("Add");
        jLabel_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 37, -1, -1));

        add_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/cart/add.png"))); // NOI18N
        add_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(add_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 27, -1, -1));

        button_add_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_add_dMouseClicked(evt);
            }
        });
        button_add_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_add_dActionPerformed(evt);
            }
        });
        jPanel2.add(button_add_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 14, 100, 67));

        add_menu_d.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        add_menu_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_menu_dMouseClicked(evt);
            }
        });
        add_menu_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_menu_dActionPerformed(evt);
            }
        });
        jPanel2.add(add_menu_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 82, 47));

        jLabel_del.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel_del.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_del.setText("Del");
        jLabel_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 36, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/cart/x.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 27, -1, -1));

        del_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/cart/del.png"))); // NOI18N
        del_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(del_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 28, -1, -1));

        button_del_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_del_dMouseClicked(evt);
            }
        });
        button_del_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_del_dActionPerformed(evt);
            }
        });
        jPanel2.add(button_del_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 14, 100, 67));

        del_menu_d.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        del_menu_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                del_menu_dMouseClicked(evt);
            }
        });
        del_menu_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_menu_dActionPerformed(evt);
            }
        });
        jPanel2.add(del_menu_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 24, 82, 47));

        javax.swing.GroupLayout panel_drink_b1Layout = new javax.swing.GroupLayout(panel_drink_b1);
        panel_drink_b1.setLayout(panel_drink_b1Layout);
        panel_drink_b1Layout.setHorizontalGroup(
            panel_drink_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_drink_b1Layout.setVerticalGroup(
            panel_drink_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_drink_b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_drink_b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_add_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_add_dMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_add_dMouseClicked

    private void button_add_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_add_dActionPerformed

    private void add_menu_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_menu_dMouseClicked

    }//GEN-LAST:event_add_menu_dMouseClicked

    private void add_menu_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_menu_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_menu_dActionPerformed

    private void button_del_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_del_dMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_del_dMouseClicked

    private void button_del_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_del_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_del_dActionPerformed

    private void del_menu_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del_menu_dMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_del_menu_dMouseClicked

    private void del_menu_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_menu_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_menu_dActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBbrandd;
    private javax.swing.JLabel LBitemNamed;
    private javax.swing.JLabel LBpriced;
    private javax.swing.JLabel add_icon;
    private FT_menu.navbar.Button_circle add_menu_d;
    private FT_menu.navbar.Button_circle button_add_d;
    private FT_menu.navbar.Button_circle button_del_d;
    private javax.swing.JLabel del_icon;
    private FT_menu.navbar.Button_circle del_menu_d;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_add;
    private javax.swing.JLabel jLabel_del;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private FT_menu.drink.PanelItem_drink panelItem_drink1;
    private FT_menu.drink.Panel_drink_b panel_drink_b1;
    private javax.swing.JTextPane txtpDescriptiond;
    // End of variables declaration//GEN-END:variables
}
