/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FT_menu.drink;

import FT_menu.drink.Drink_data;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.DecimalFormat;

/**
 *
 * @author mario
 */
public class Item_drink extends javax.swing.JPanel {

    /**
     * Creates new form Item
     */
    
    private boolean selected;
    
    public boolean isSelected() {
        return selected;
    }
    
    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }
    
    public Item_drink() {
        initComponents();
        setOpaque(false);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    private Drink_data data_d;

    public Drink_data getData() {
        return data_d;
    }
    
    public void setData(Drink_data data_d) {
        this.data_d = data_d;
        pic.setImage(data_d.getImage_d());
        LBitemName_d.setText(data_d.getItemName_d());
        LBdescription_d.setText(data_d.getDescription_d());
        LBbrand_d.setText(data_d.getBrandName_d());
        DecimalFormat df = new DecimalFormat("Rp#,###");
        LBprice_d.setText(df.format(data_d.getPrice_d()));
    }
    
    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D)grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(250, 250, 250));
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
        if (selected) {
             g2.setColor(new Color(0, 0, 255));
             g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
        }
        
        g2.dispose();
        super.paint(grphcs);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBitemName_d = new javax.swing.JLabel();
        LBdescription_d = new javax.swing.JLabel();
        pic = new FT_menu.PictureBox();
        LBprice_d = new javax.swing.JLabel();
        LBbrand_d = new javax.swing.JLabel();

        LBitemName_d.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LBitemName_d.setForeground(new java.awt.Color(91, 91, 91));
        LBitemName_d.setText("Item Name");

        LBdescription_d.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LBdescription_d.setForeground(new java.awt.Color(135, 135, 135));
        LBdescription_d.setText("Description");

        pic.setImage(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/img4.png"))); // NOI18N

        LBprice_d.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        LBprice_d.setForeground(new java.awt.Color(91, 91, 91));
        LBprice_d.setText("Rp.0.000");

        LBbrand_d.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LBbrand_d.setForeground(new java.awt.Color(77, 77, 77));
        LBbrand_d.setText("Brand");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBprice_d))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LBitemName_d, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LBdescription_d, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LBbrand_d)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LBitemName_d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBdescription_d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBprice_d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBbrand_d)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBbrand_d;
    private javax.swing.JLabel LBdescription_d;
    private javax.swing.JLabel LBitemName_d;
    private javax.swing.JLabel LBprice_d;
    private FT_menu.PictureBox pic;
    // End of variables declaration//GEN-END:variables
}
