/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FT_menu.food;

import FT_menu.ScrollBar;
import FT_menu.navbar.Button_circle;
import java.awt.Component;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import javax.swing.SwingUtilities;

/**
 *
 * @author mario
 */
public class Food_home extends javax.swing.JPanel {

    /**
     * Creates new form Food_home
     */
    private Event_food event;

    public void setEvent(Event_food event) {
        this.event = event;
    }
    
    public Food_home() {
        initComponents();
        jScrollPane.setVerticalScrollBar(new ScrollBar());        
    }
    
    public void addItem(Food_data data_f) {
        Item_food itemf = new Item_food();
        itemf.setData(data_f);
        itemf.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                if (SwingUtilities.isLeftMouseButton(me)) {
                    event.itemClick(itemf, data_f);
                }
            }
        
        });
        panelItem_food.add(itemf);
        panelItem_food.repaint();
        panelItem_food.revalidate();
    }
    
    public void setSelected(Component item) {
        for (Component com : panelItem_food.getComponents()) {
            Item_food i = (Item_food) com;
            if (i.isSelected()) {
                i.setSelected(false);
            }
        }
        ((Item_food) item).setSelected(true);
    }
    
    public void showItem(Food_data data_f) {
        LBitemNamef.setText(data_f.getItemName_f());
        txtpDescriptionf.setText(data_f.getDescription_f());
        LBbrandf.setText(data_f.getBrandName_f());
        DecimalFormat df = new DecimalFormat("Rp#,###");
        LBpricef.setText(df.format(data_f.getPrice_f()));
        //LBpricef.setText(String.valueOf(data_f.getPrice_f()));
    }
    
    public Point getPanelItemLocation() {
        Point p = jScrollPane.getLocation();
        return new Point(p.x, p.y-jScrollPane.getViewport().getViewPosition().y);
    }
    
    public Button_circle getButton_add_f() {
        return button_add_f;
    }
    
    public Button_circle getButton_del_f() {
        return button_del_f;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        panelItem_food = new FT_menu.food.PanelItem_food();
        jPanel1 = new javax.swing.JPanel();
        LBitemNamef = new javax.swing.JLabel();
        LBpricef = new javax.swing.JLabel();
        LBbrandf = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtpDescriptionf = new javax.swing.JTextPane();
        panel_food_b1 = new FT_menu.food.Panel_food_b();
        jPanel2 = new javax.swing.JPanel();
        jLabel_add = new javax.swing.JLabel();
        cart_icon = new javax.swing.JLabel();
        button_add_f = new FT_menu.navbar.Button_circle();
        add_menu_f = new FT_menu.navbar.Button_circle();
        jLabel1 = new javax.swing.JLabel();
        jLabel_del = new javax.swing.JLabel();
        del_icon = new javax.swing.JLabel();
        button_del_f = new FT_menu.navbar.Button_circle();
        del_menu_f = new FT_menu.navbar.Button_circle();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1150, 675));

        jScrollPane.setBorder(null);
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelItem_food.setBackground(new java.awt.Color(255, 255, 255));
        panelItem_food.setOpaque(false);
        jScrollPane.setViewportView(panelItem_food);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        LBitemNamef.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LBitemNamef.setForeground(new java.awt.Color(91, 91, 91));
        LBitemNamef.setText("Food");

        LBpricef.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        LBpricef.setForeground(new java.awt.Color(91, 91, 91));
        LBpricef.setText("Rp.0.000");

        LBbrandf.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LBbrandf.setForeground(new java.awt.Color(87, 87, 87));
        LBbrandf.setText("Tipe");

        txtpDescriptionf.setBorder(null);
        txtpDescriptionf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtpDescriptionf.setForeground(new java.awt.Color(145, 145, 145));
        txtpDescriptionf.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtpDescriptionf, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBitemNamef, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBbrandf)
                                    .addComponent(LBpricef, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBitemNamef)
                .addGap(9, 9, 9)
                .addComponent(LBpricef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBbrandf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpDescriptionf, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_food_b1.setBlur(jPanel2);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_add.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel_add.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_add.setText("Add");
        jLabel_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 37, -1, -1));

        cart_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/cart/add.png"))); // NOI18N
        cart_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(cart_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 27, -1, -1));

        button_add_f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_add_fMouseClicked(evt);
            }
        });
        button_add_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_add_fActionPerformed(evt);
            }
        });
        jPanel2.add(button_add_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 14, 100, 67));

        add_menu_f.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        add_menu_f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_menu_fMouseClicked(evt);
            }
        });
        add_menu_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_menu_fActionPerformed(evt);
            }
        });
        jPanel2.add(add_menu_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 82, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/cart/x.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 28, -1, -1));

        jLabel_del.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel_del.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_del.setText("Del");
        jLabel_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 37, -1, -1));

        del_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/cart/del.png"))); // NOI18N
        del_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(del_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        button_del_f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_del_fMouseClicked(evt);
            }
        });
        button_del_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_del_fActionPerformed(evt);
            }
        });
        jPanel2.add(button_del_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 15, 100, 67));

        del_menu_f.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        del_menu_f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                del_menu_fMouseClicked(evt);
            }
        });
        del_menu_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_menu_fActionPerformed(evt);
            }
        });
        jPanel2.add(del_menu_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 25, 82, 47));

        javax.swing.GroupLayout panel_food_b1Layout = new javax.swing.GroupLayout(panel_food_b1);
        panel_food_b1.setLayout(panel_food_b1Layout);
        panel_food_b1Layout.setHorizontalGroup(
            panel_food_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_food_b1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_food_b1Layout.setVerticalGroup(
            panel_food_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_food_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_food_b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_menu_fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_menu_fMouseClicked

    }//GEN-LAST:event_add_menu_fMouseClicked

    private void add_menu_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_menu_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_menu_fActionPerformed

    private void button_add_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_add_fActionPerformed

    private void button_add_fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_add_fMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_add_fMouseClicked

    private void button_del_fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_del_fMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_del_fMouseClicked

    private void button_del_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_del_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_del_fActionPerformed

    private void del_menu_fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del_menu_fMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_del_menu_fMouseClicked

    private void del_menu_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_menu_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_menu_fActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBbrandf;
    private javax.swing.JLabel LBitemNamef;
    private javax.swing.JLabel LBpricef;
    private FT_menu.navbar.Button_circle add_menu_f;
    private FT_menu.navbar.Button_circle button_add_f;
    private FT_menu.navbar.Button_circle button_del_f;
    private javax.swing.JLabel cart_icon;
    private javax.swing.JLabel del_icon;
    private FT_menu.navbar.Button_circle del_menu_f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_add;
    private javax.swing.JLabel jLabel_del;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private FT_menu.food.PanelItem_food panelItem_food;
    private FT_menu.food.Panel_food_b panel_food_b1;
    private javax.swing.JTextPane txtpDescriptionf;
    // End of variables declaration//GEN-END:variables
}
