/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FT_menu.food;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.DecimalFormat;

/**
 *
 * @author mario
 */
public class Item_food extends javax.swing.JPanel {

    /**
     * Creates new form Item_food
     */
    
    private boolean selected;
    
    public boolean isSelected() {
        return selected;
    }
    
    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }
    
    public Item_food() {
        initComponents();
        setOpaque(false);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    private Food_data data_f;

    public Food_data getData() {
        return data_f;
    }
    
    public void setData(Food_data data_f) {
        this.data_f = data_f;
        picf.setImage(data_f.getImage_f());
        LBitemName_f.setText(data_f.getItemName_f());
        LBdescription_f.setText(data_f.getDescription_f());
        LBbrand_f.setText(data_f.getBrandName_f());
        DecimalFormat df = new DecimalFormat("Rp#,###");
        LBprice_f.setText(df.format(data_f.getPrice_f()));
    }
    
    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D)grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(250, 250, 250));
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
        if (selected) {
             g2.setColor(new Color(0, 0, 255));
             g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
        }
        
        g2.dispose();
        super.paint(grphcs);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBitemName_f = new javax.swing.JLabel();
        LBdescription_f = new javax.swing.JLabel();
        picf = new FT_menu.PictureBox();
        LBprice_f = new javax.swing.JLabel();
        LBbrand_f = new javax.swing.JLabel();

        LBitemName_f.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LBitemName_f.setForeground(new java.awt.Color(91, 91, 91));
        LBitemName_f.setText("Item Name");

        LBdescription_f.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LBdescription_f.setForeground(new java.awt.Color(135, 135, 135));
        LBdescription_f.setText("Description");

        picf.setImage(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/img2.png"))); // NOI18N

        LBprice_f.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        LBprice_f.setForeground(new java.awt.Color(91, 91, 91));
        LBprice_f.setText("Rp.0.000");

        LBbrand_f.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LBbrand_f.setForeground(new java.awt.Color(77, 77, 77));
        LBbrand_f.setText("Brand");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LBitemName_f, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LBdescription_f, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LBbrand_f)
                            .addGap(70, 70, 70)
                            .addComponent(LBprice_f))
                        .addComponent(picf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LBitemName_f)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBdescription_f)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(picf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBprice_f)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(LBbrand_f)
                        .addGap(15, 15, 15))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBbrand_f;
    private javax.swing.JLabel LBdescription_f;
    private javax.swing.JLabel LBitemName_f;
    private javax.swing.JLabel LBprice_f;
    private FT_menu.PictureBox picf;
    // End of variables declaration//GEN-END:variables
}
