/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FT_menu.checkout;

import FT_menu.ScrollBar;
import FT_menu.navbar.Button_circle;
import G_Swing.TextField;
import javax.swing.JPanel;
import javax.swing.JTextPane;

/**
 *
 * @author mario
 */
public class Checkout_home extends javax.swing.JPanel {

    /**
     * Creates new form Checkout_home
     */
    
   // private Checkout_data C_data;
    
    
    
    public Checkout_home() {
        initComponents();
        background_checkout1.addBlurComponent(Panel1);
        background_checkout1.addBlurComponent(deliv);
        jScrollPane1.setVerticalScrollBar(new ScrollBar());
        jScrollPane1.setHorizontalScrollBar(new ScrollBar());
    }
    
    public Button_circle getButton_cancel_c() {
        return button_cancel_c;
    }
    
    public JTextPane getCheckout_pane() {
        return checkout_pane;
    }
    
    public  Button_circle getButton_stay_c() {
        return button_stay_c;
    }
    
    public JPanel getOnsite_b() {
        return onSite_b;
    }
    
    public JPanel getQuote_c() {
        return quote_c;
    }
    
    public Button_circle getButton_deliv_c() {
        return button_deliv_c;
    }
    
    public JPanel getDeliv_a() {
        return deliv_a;
    }
    
    public JPanel getDeliv_b() {
        return deliv_b;
    }
    
    public Button_circle getButton_cashless_c() {
        return button_cashless_c;
    }
    
    public JPanel getQuote_c1() {
        return quote_c1;
    }
    
    public Button_circle getButton_cash() {
        return button_cash;
    }
    
    public Button_circle getButton_cashless() {
        return button_cashless;
    }
    
    public TextField getNama_deliv() {
        return txtnama_deliv;
    }
    
    public  TextField getContact_deliv() {
        return txtcontact_deliv;
    }
    
    public TextField getAlamat_deliv() {
        return txtalamat_deliv;
    }
    
    public TextField_checkout getAlamat_descrp() {
        return txtdeskripsiA_deliv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_checkout1 = new FT_menu.checkout.Background_checkout();
        Panel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkout_pane = new javax.swing.JTextPane();
        onSite_b = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        button_cash = new FT_menu.navbar.Button_circle();
        button_circle_black2 = new FT_menu.navbar.Button_circle_black();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        button_cashless = new FT_menu.navbar.Button_circle();
        button_circle_black3 = new FT_menu.navbar.Button_circle_black();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        quote_c = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        deliv = new javax.swing.JPanel();
        deliv_a = new javax.swing.JPanel();
        txtnama_deliv = new G_Swing.TextField();
        txtcontact_deliv = new G_Swing.TextField();
        txtdeskripsiA_deliv = new FT_menu.checkout.TextField_checkout();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtalamat_deliv = new G_Swing.TextField();
        quote_c1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        deliv_b = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        button_cashless_c = new FT_menu.navbar.Button_circle();
        button_circle_black1 = new FT_menu.navbar.Button_circle_black();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        button_deliv_c = new FT_menu.navbar.Button_circle();
        button_circle3 = new FT_menu.navbar.Button_circle();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        button_stay_c = new FT_menu.navbar.Button_circle();
        button_circle5 = new FT_menu.navbar.Button_circle();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        button_cancel_c = new FT_menu.navbar.Button_circle();
        button_circle1 = new FT_menu.navbar.Button_circle();

        setPreferredSize(new java.awt.Dimension(1650, 1020));

        Panel1.setOpaque(false);

        checkout_pane.setEditable(false);
        checkout_pane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        checkout_pane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(checkout_pane);

        onSite_b.setBackground(new java.awt.Color(0, 153, 153));
        onSite_b.setOpaque(false);
        onSite_b.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/checkout/image/Rp-1.png"))); // NOI18N
        onSite_b.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Cash");
        onSite_b.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 86, -1, -1));
        onSite_b.add(button_cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 210, 70));
        onSite_b.add(button_circle_black2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 90));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/checkout/image/Cc-1.png"))); // NOI18N
        onSite_b.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("Cashless");
        onSite_b.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 205, -1, -1));

        button_cashless.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_cashlessMouseClicked(evt);
            }
        });
        onSite_b.add(button_cashless, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 70));
        onSite_b.add(button_circle_black3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 250, 90));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Happy taste, pastikan untuk selalu cek ulang");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("agar tak ada menu lezat yang terlewat.");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 360, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bangun moodmu dengan makan lezat dan");
        jLabel8.setToolTipText("");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 360, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("jalani hari dengan penuh semangat.");
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 360, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Selamat menikkmati :).");
        jLabel24.setToolTipText("");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel24.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 360, -1));

        quote_c.setBackground(new java.awt.Color(0, 102, 102));
        quote_c.setForeground(new java.awt.Color(255, 255, 255));
        quote_c.setOpaque(false);
        quote_c.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Don't let hunger ruin your day");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        quote_c.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(onSite_b, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                                .addComponent(quote_c, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))))))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(onSite_b, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quote_c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(62, 62, 62))
        );

        deliv.setBackground(new java.awt.Color(0, 153, 204));
        deliv.setOpaque(false);

        deliv_a.setBackground(new java.awt.Color(0, 51, 51));
        deliv_a.setOpaque(false);

        txtnama_deliv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnama_deliv.setHint("Nama Lengkap");
        txtnama_deliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama_delivActionPerformed(evt);
            }
        });

        txtcontact_deliv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcontact_deliv.setHint("No Hp/Telp");

        txtdeskripsiA_deliv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdeskripsiA_deliv.setHint("Deskripsi Alamat tambahan");
        txtdeskripsiA_deliv.setName(""); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mohon maaf, untuk saat ini");
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("hanya tersedia opsi pemabayaran cashless");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("untuk pemesanan yang diantar ke alamat.");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtalamat_deliv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtalamat_deliv.setHint("Alamat");

        javax.swing.GroupLayout deliv_aLayout = new javax.swing.GroupLayout(deliv_a);
        deliv_a.setLayout(deliv_aLayout);
        deliv_aLayout.setHorizontalGroup(
            deliv_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliv_aLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtnama_deliv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(deliv_aLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtcontact_deliv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(deliv_aLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtdeskripsiA_deliv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(deliv_aLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(138, 138, 138))
            .addGroup(deliv_aLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(deliv_aLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliv_aLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtalamat_deliv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        deliv_aLayout.setVerticalGroup(
            deliv_aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliv_aLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtnama_deliv, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(txtcontact_deliv, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(txtalamat_deliv, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(txtdeskripsiA_deliv, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(80, 80, 80)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );

        quote_c1.setBackground(new java.awt.Color(0, 102, 102));
        quote_c1.setOpaque(false);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nothing brings people together");
        jLabel23.setToolTipText("");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel23.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("like good food....");
        jLabel25.setToolTipText("");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel25.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 51));
        jLabel26.setText("There is no sincere love than");
        jLabel26.setToolTipText("");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel26.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("STXingkai", 0, 26)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 51));
        jLabel28.setText("Happyness is Food....");
        jLabel28.setToolTipText("");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel28.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 51));
        jLabel29.setText("Food is not Fools.");
        jLabel29.setToolTipText("");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel29.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("STXingkai", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 51, 51));
        jLabel30.setText("the love of food.");
        jLabel30.setToolTipText("");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel30.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout quote_c1Layout = new javax.swing.GroupLayout(quote_c1);
        quote_c1.setLayout(quote_c1Layout);
        quote_c1Layout.setHorizontalGroup(
            quote_c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(quote_c1Layout.createSequentialGroup()
                .addGroup(quote_c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quote_c1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(quote_c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(quote_c1Layout.createSequentialGroup()
                        .addGroup(quote_c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quote_c1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(quote_c1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        quote_c1Layout.setVerticalGroup(
            quote_c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quote_c1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(jLabel25)
                .addGap(92, 92, 92)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout delivLayout = new javax.swing.GroupLayout(deliv);
        deliv.setLayout(delivLayout);
        delivLayout.setHorizontalGroup(
            delivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delivLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deliv_a, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(quote_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        delivLayout.setVerticalGroup(
            delivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delivLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(deliv_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(delivLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(quote_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deliv_b.setBackground(new java.awt.Color(0, 204, 204));
        deliv_b.setOpaque(false);
        deliv_b.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/checkout/image/Cc-1.png"))); // NOI18N
        jLabel16.setText("\n");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deliv_b.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 35, -1, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("Cashless");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deliv_b.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        button_cashless_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_cashless_cMouseClicked(evt);
            }
        });
        button_cashless_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cashless_cActionPerformed(evt);
            }
        });
        deliv_b.add(button_cashless_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, 60));
        deliv_b.add(button_circle_black1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 270, 80));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/checkout/image/wind.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/checkout/image/deliv.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Delivery Home");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));
        jPanel2.add(button_deliv_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 270, 80));

        button_circle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_circle3ActionPerformed(evt);
            }
        });
        jPanel2.add(button_circle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 230, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/checkout/image/rest.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/checkout/image/loc.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("On Restaurants");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 40, -1, -1));
        jPanel2.add(button_stay_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 270, 80));

        button_circle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_circle5ActionPerformed(evt);
            }
        });
        jPanel2.add(button_circle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 230, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/checkout/image/cancelled_5267928.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 34, -1, 40));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Cancel");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 42, -1, -1));
        jPanel2.add(button_cancel_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 190, 85));
        jPanel2.add(button_circle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, 64));

        javax.swing.GroupLayout background_checkout1Layout = new javax.swing.GroupLayout(background_checkout1);
        background_checkout1.setLayout(background_checkout1Layout);
        background_checkout1Layout.setHorizontalGroup(
            background_checkout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, background_checkout1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(background_checkout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
                    .addGroup(background_checkout1Layout.createSequentialGroup()
                        .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48)))
                .addGroup(background_checkout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_checkout1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(deliv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(background_checkout1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(deliv_b, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        background_checkout1Layout.setVerticalGroup(
            background_checkout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_checkout1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(background_checkout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_checkout1Layout.createSequentialGroup()
                        .addComponent(deliv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background_checkout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliv_b, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(229, 229, 229))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_checkout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_checkout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_circle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_circle3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_circle3ActionPerformed

    private void button_cashless_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cashless_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_cashless_cActionPerformed

    private void button_circle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_circle5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_circle5ActionPerformed

    private void txtnama_delivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama_delivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnama_delivActionPerformed

    private void button_cashlessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cashlessMouseClicked
       
    }//GEN-LAST:event_button_cashlessMouseClicked

    private void button_cashless_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cashless_cMouseClicked

    }//GEN-LAST:event_button_cashless_cMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private FT_menu.checkout.Background_checkout background_checkout1;
    private FT_menu.navbar.Button_circle button_cancel_c;
    private FT_menu.navbar.Button_circle button_cash;
    private FT_menu.navbar.Button_circle button_cashless;
    private FT_menu.navbar.Button_circle button_cashless_c;
    private FT_menu.navbar.Button_circle button_circle1;
    private FT_menu.navbar.Button_circle button_circle3;
    private FT_menu.navbar.Button_circle button_circle5;
    private FT_menu.navbar.Button_circle_black button_circle_black1;
    private FT_menu.navbar.Button_circle_black button_circle_black2;
    private FT_menu.navbar.Button_circle_black button_circle_black3;
    private FT_menu.navbar.Button_circle button_deliv_c;
    private FT_menu.navbar.Button_circle button_stay_c;
    private javax.swing.JTextPane checkout_pane;
    private javax.swing.JPanel deliv;
    private javax.swing.JPanel deliv_a;
    private javax.swing.JPanel deliv_b;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel onSite_b;
    private javax.swing.JPanel quote_c;
    private javax.swing.JPanel quote_c1;
    private G_Swing.TextField txtalamat_deliv;
    private G_Swing.TextField txtcontact_deliv;
    private FT_menu.checkout.TextField_checkout txtdeskripsiA_deliv;
    private G_Swing.TextField txtnama_deliv;
    // End of variables declaration//GEN-END:variables
}
