/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FT_regist;

import FT_login.login;
import java.sql.*;
import G_Conection.Conection;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    
    public register() throws Exception {
        initComponents();
        FT_regist.Button_reg buttonReg = new FT_regist.Button_reg();
        add(buttonReg);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_Regist2 = new FT_regist.Background_Regist();
        jPanel1 = new javax.swing.JPanel();
        reg_f_name = new G_Swing.TextField();
        reg_L_name = new G_Swing.TextField();
        reg_addrs = new G_Swing.TextField();
        reg_noHP = new G_Swing.TextField();
        reg_email = new G_Swing.TextField();
        reg_username = new G_Swing.TextField();
        reg_pass = new G_Swing.PasswordField();
        button_reg1 = new FT_regist.Button_reg();
        button_reg2 = new FT_regist.Button_reg();
        reg_penanda = new G_Swing.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1650, 1020));

        background_Regist2.setBlur(jPanel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        reg_f_name.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        reg_f_name.setHint("Nama depan");
        reg_f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_f_nameActionPerformed(evt);
            }
        });
        reg_f_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reg_f_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reg_f_nameKeyReleased(evt);
            }
        });

        reg_L_name.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        reg_L_name.setHint("Nama belakang");
        reg_L_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_L_nameActionPerformed(evt);
            }
        });
        reg_L_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reg_L_nameKeyPressed(evt);
            }
        });

        reg_addrs.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        reg_addrs.setHint("Alamat");
        reg_addrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reg_addrsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reg_addrsKeyReleased(evt);
            }
        });

        reg_noHP.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        reg_noHP.setHint("Phone Number");
        reg_noHP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reg_noHPKeyPressed(evt);
            }
        });

        reg_email.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        reg_email.setHint("Email");
        reg_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reg_emailKeyPressed(evt);
            }
        });

        reg_username.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        reg_username.setHint("Username");
        reg_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reg_usernameKeyPressed(evt);
            }
        });

        reg_pass.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        reg_pass.setHint("Password");
        reg_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reg_passKeyPressed(evt);
            }
        });

        button_reg1.setForeground(new java.awt.Color(255, 255, 255));
        button_reg1.setText("REGISTER");
        button_reg1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        button_reg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_reg1MouseClicked(evt);
            }
        });
        button_reg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_reg1ActionPerformed(evt);
            }
        });

        button_reg2.setForeground(new java.awt.Color(255, 255, 255));
        button_reg2.setText("Cancel");
        button_reg2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        button_reg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_reg2MouseClicked(evt);
            }
        });

        reg_penanda.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        reg_penanda.setHint("Penanda akun");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reg_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(reg_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reg_addrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reg_f_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reg_L_name, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(reg_noHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reg_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reg_penanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(button_reg2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button_reg1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_f_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reg_L_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_addrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reg_noHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reg_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reg_penanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(button_reg1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_reg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout background_Regist2Layout = new javax.swing.GroupLayout(background_Regist2);
        background_Regist2.setLayout(background_Regist2Layout);
        background_Regist2Layout.setHorizontalGroup(
            background_Regist2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_Regist2Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        background_Regist2Layout.setVerticalGroup(
            background_Regist2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background_Regist2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_Regist2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_Regist2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reg_f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_f_nameActionPerformed

    private void reg_L_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_L_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_L_nameActionPerformed

    private void button_reg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_reg1ActionPerformed
        String noHP = reg_noHP.getText().trim();
        if (!noHP.isEmpty()) {
            try {
                long no_HP = Long.parseLong(noHP);
                char[] password = reg_pass.getPassword();
                String pass = new String(password);

                String sql = "INSERT INTO user_reek (nama_depan, nama_belakang, alamat, nomer_phone, email, username, password, penanda) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                try ( PreparedStatement ps = Conection.conection().prepareStatement(sql)) {
                    ps.setString(1, reg_f_name.getText());
                    ps.setString(2, reg_L_name.getText());
                    ps.setString(3, reg_addrs.getText());
                    ps.setLong(4, no_HP);                                       // Menggunakan setLong untuk nomer_phone, karena data banyak
                    ps.setString(5, reg_email.getText());
                    ps.setString(6, reg_username.getText());
                    ps.setString(7, pass);
                    ps.setString(8, reg_penanda.getText());
                    ps.executeUpdate();

                    login log = new login();
                    this.setVisible(false);
                    log.setVisible(true);
                } catch (SQLException e) {
                    e.printStackTrace();
                } catch (Exception ex) {
                    Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (NumberFormatException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Nomor telepon harus berupa angka", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "tidak boleh ada data yang kosong", "Information", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_button_reg1ActionPerformed
 
        
    private void button_reg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_reg1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_reg1MouseClicked

    private void button_reg2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_reg2MouseClicked
        try {
            login log = new login();
            this.setVisible(false);
            log.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_button_reg2MouseClicked

    private void reg_f_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reg_f_nameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            reg_L_name.requestFocus();
        }
    }//GEN-LAST:event_reg_f_nameKeyPressed

    private void reg_L_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reg_L_nameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            reg_addrs.requestFocus();
        }
    }//GEN-LAST:event_reg_L_nameKeyPressed

    private void reg_f_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reg_f_nameKeyReleased
        
    }//GEN-LAST:event_reg_f_nameKeyReleased

    private void reg_addrsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reg_addrsKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_addrsKeyReleased

    private void reg_addrsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reg_addrsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            reg_noHP.requestFocus();
        }
    }//GEN-LAST:event_reg_addrsKeyPressed

    private void reg_noHPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reg_noHPKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            reg_email.requestFocus();
        }
    }//GEN-LAST:event_reg_noHPKeyPressed

    private void reg_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reg_usernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            reg_pass.requestFocus();
        }
    }//GEN-LAST:event_reg_usernameKeyPressed

    private void reg_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reg_emailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            reg_username.requestFocus();
        }
    }//GEN-LAST:event_reg_emailKeyPressed

    private void reg_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reg_passKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            reg_penanda.requestFocus();
        }
    }//GEN-LAST:event_reg_passKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new register().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FT_regist.Background_Regist background_Regist2;
    private FT_regist.Button_reg button_reg1;
    private FT_regist.Button_reg button_reg2;
    private javax.swing.JPanel jPanel1;
    private G_Swing.TextField reg_L_name;
    private G_Swing.TextField reg_addrs;
    private G_Swing.TextField reg_email;
    private G_Swing.TextField reg_f_name;
    private G_Swing.TextField reg_noHP;
    private G_Swing.PasswordField reg_pass;
    private G_Swing.TextField reg_penanda;
    private G_Swing.TextField reg_username;
    // End of variables declaration//GEN-END:variables
}
