/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FT_menu.desert;

import FT_menu.ScrollBar;
import FT_menu.navbar.Button_circle;
import java.awt.Component;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import javax.swing.SwingUtilities;

/**
 *
 * @author mario
 */
public class Desert_home extends javax.swing.JPanel {

    /**
     * Creates new form Desert_home
     */
    private Event_desert event;
    
    public Desert_home() {
        initComponents();
        jScrollPane1.setVerticalScrollBar(new ScrollBar());
    }
    
    public void setEvent(Event_desert event) {
        this.event = event;
    }
    
    public void addItem(Desert_data data_s) {
        Item_desert item_s = new Item_desert();
        item_s.setData(data_s);
        item_s.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                if (SwingUtilities.isLeftMouseButton(me)) {
                event.itemClick(item_s, data_s);
                }
            }
        });
        panelItem_desert1.add(item_s);
        panelItem_desert1.repaint();
        panelItem_desert1.revalidate();
    }
    
    public void setSelected(Component item) {
        for (Component com : panelItem_desert1.getComponents()) {
            Item_desert i = (Item_desert) com;
            if (i.isSelected()) {
                i.setSelected(false);
            }
        }
        ((Item_desert) item).setSelected(true);
    }
    
    public void showItem(Desert_data data_s) {
        LBitemName_s.setText(data_s.getItemName_s());
        txtDescription_s.setText(data_s.getDescription_s());
        LBbrand_s.setText(data_s.getBrandName_s());
        DecimalFormat df = new DecimalFormat("Rp#,###");
        LBprice_s.setText(df.format(data_s.getPrice_s()));
    }
    
    public Point getpanelItemLocation() {
        Point p = jScrollPane1.getLocation();
        return new Point(p.x, p.y-jScrollPane1.getViewport().getViewPosition().y);
    }
    
    public Button_circle getButton_add_s() {
        return button_add_s;
    }
    
    public Button_circle getButton_del_s() {
        return button_del_s;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelItem_desert1 = new FT_menu.desert.PanelItem_desert();
        jPanel1 = new javax.swing.JPanel();
        LBitemName_s = new javax.swing.JLabel();
        LBprice_s = new javax.swing.JLabel();
        LBbrand_s = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtDescription_s = new javax.swing.JTextPane();
        panel_desert_b1 = new FT_menu.desert.Panel_desert_b();
        jPanel2 = new javax.swing.JPanel();
        jLabel_del = new javax.swing.JLabel();
        jLabel_add = new javax.swing.JLabel();
        add_icon = new javax.swing.JLabel();
        button_add_s = new FT_menu.navbar.Button_circle();
        add_menu_s = new FT_menu.navbar.Button_circle();
        jLabel1 = new javax.swing.JLabel();
        del_icon = new javax.swing.JLabel();
        button_del_s = new FT_menu.navbar.Button_circle();
        del_menu_s = new FT_menu.navbar.Button_circle();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1650, 1020));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setViewportView(panelItem_desert1);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(306, 404));

        LBitemName_s.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LBitemName_s.setForeground(new java.awt.Color(91, 91, 91));
        LBitemName_s.setText("Desert");

        LBprice_s.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        LBprice_s.setForeground(new java.awt.Color(91, 91, 91));
        LBprice_s.setText("Rp.0.000");

        LBbrand_s.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LBbrand_s.setForeground(new java.awt.Color(77, 77, 77));
        LBbrand_s.setText("Tipe");

        txtDescription_s.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBitemName_s, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBprice_s)
                            .addComponent(LBbrand_s))
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addComponent(txtDescription_s))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBitemName_s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBprice_s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBbrand_s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescription_s, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        panel_desert_b1.setBlur(jPanel2);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_del.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel_del.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_del.setText("Del");
        jLabel_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 36, -1, -1));

        jLabel_add.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel_add.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_add.setText("Add");
        jLabel_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 37, -1, -1));

        add_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/cart/add.png"))); // NOI18N
        add_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(add_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 27, -1, -1));

        button_add_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_add_sMouseClicked(evt);
            }
        });
        button_add_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_add_sActionPerformed(evt);
            }
        });
        jPanel2.add(button_add_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 14, 100, 67));

        add_menu_s.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        add_menu_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_menu_sMouseClicked(evt);
            }
        });
        add_menu_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_menu_sActionPerformed(evt);
            }
        });
        jPanel2.add(add_menu_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 82, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/cart/x.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 28, -1, -1));

        del_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/cart/del.png"))); // NOI18N
        del_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(del_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 28, -1, -1));

        button_del_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_del_sMouseClicked(evt);
            }
        });
        button_del_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_del_sActionPerformed(evt);
            }
        });
        jPanel2.add(button_del_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 13, 100, 67));

        del_menu_s.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        del_menu_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                del_menu_sMouseClicked(evt);
            }
        });
        del_menu_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_menu_sActionPerformed(evt);
            }
        });
        jPanel2.add(del_menu_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 24, 82, 47));

        javax.swing.GroupLayout panel_desert_b1Layout = new javax.swing.GroupLayout(panel_desert_b1);
        panel_desert_b1.setLayout(panel_desert_b1Layout);
        panel_desert_b1Layout.setHorizontalGroup(
            panel_desert_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_desert_b1Layout.setVerticalGroup(
            panel_desert_b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_desert_b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_desert_b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_add_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_add_sMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_add_sMouseClicked

    private void button_add_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_add_sActionPerformed

    private void add_menu_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_menu_sMouseClicked

    }//GEN-LAST:event_add_menu_sMouseClicked

    private void add_menu_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_menu_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_menu_sActionPerformed

    private void button_del_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_del_sMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_del_sMouseClicked

    private void button_del_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_del_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_del_sActionPerformed

    private void del_menu_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del_menu_sMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_del_menu_sMouseClicked

    private void del_menu_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_menu_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_del_menu_sActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBbrand_s;
    private javax.swing.JLabel LBitemName_s;
    private javax.swing.JLabel LBprice_s;
    private javax.swing.JLabel add_icon;
    private FT_menu.navbar.Button_circle add_menu_s;
    private FT_menu.navbar.Button_circle button_add_s;
    private FT_menu.navbar.Button_circle button_del_s;
    private javax.swing.JLabel del_icon;
    private FT_menu.navbar.Button_circle del_menu_s;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_add;
    private javax.swing.JLabel jLabel_del;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private FT_menu.desert.PanelItem_desert panelItem_desert1;
    private FT_menu.desert.Panel_desert_b panel_desert_b1;
    private javax.swing.JTextPane txtDescription_s;
    // End of variables declaration//GEN-END:variables
}
