/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FT_menu.desert;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.DecimalFormat;

/**
 *
 * @author mario
 */
public class Item_desert extends javax.swing.JPanel {

    /**
     * Creates new form Item
     */
    
    private boolean selected;
    
    public boolean isSelected() {
        return selected;
    }
    
    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }
    
    public Item_desert() {
        initComponents();
        setOpaque(false);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    private Desert_data data_s;

    public Desert_data getData() {
        return data_s;
    }
    
    public void setData(Desert_data data_s) {
        this.data_s = data_s;
        pics.setImage(data_s.getImage_s());
        LBitemName_s.setText(data_s.getItemName_s());
        LBdescription_s.setText(data_s.getDescription_s());
        LBbrand_s.setText(data_s.getBrandName_s());
        DecimalFormat df = new DecimalFormat("Rp#,###");
        LBprice_s.setText(df.format(data_s.getPrice_s()));
    }
    
    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D)grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(250, 250, 250));
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
        if (selected) {
             g2.setColor(new Color(0, 0, 255));
             g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
        }
        
        g2.dispose();
        super.paint(grphcs);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBitemName_s = new javax.swing.JLabel();
        LBdescription_s = new javax.swing.JLabel();
        pics = new FT_menu.PictureBox();
        LBprice_s = new javax.swing.JLabel();
        LBbrand_s = new javax.swing.JLabel();

        LBitemName_s.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LBitemName_s.setForeground(new java.awt.Color(91, 91, 91));
        LBitemName_s.setText("Item Name");

        LBdescription_s.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LBdescription_s.setForeground(new java.awt.Color(135, 135, 135));
        LBdescription_s.setText("Description");

        pics.setImage(new javax.swing.ImageIcon(getClass().getResource("/FT_menu/image/img4.png"))); // NOI18N

        LBprice_s.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        LBprice_s.setForeground(new java.awt.Color(91, 91, 91));
        LBprice_s.setText("Rp.0.000");

        LBbrand_s.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LBbrand_s.setForeground(new java.awt.Color(77, 77, 77));
        LBbrand_s.setText("Brand");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBprice_s))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pics, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LBitemName_s, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LBdescription_s, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LBbrand_s)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LBitemName_s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBdescription_s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pics, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBprice_s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBbrand_s)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBbrand_s;
    private javax.swing.JLabel LBdescription_s;
    private javax.swing.JLabel LBitemName_s;
    private javax.swing.JLabel LBprice_s;
    private FT_menu.PictureBox pics;
    // End of variables declaration//GEN-END:variables
}
